server:
  port: 8080
spring:
  datasource: #数据源
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动
    url: jdbc:mysql://43.138.47.53:3306/retools?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true  # 数据库的 JDBC URL
    password: root
    username: root
  profiles:
    active: dev
---
server:
  port: 8081
spring:
  datasource: #数据源
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动
    url: jdbc:mysql://localhost:3306/retools?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true  # 数据库的 JDBC URL
    password: root
    username: root
  config:
    activate:
      on-profile: dev
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
---
server:
  port: 8082
spring:
  datasource: #数据源
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动
    url: jdbc:mysql://43.138.47.53:3306/retools?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true  # 数据库的 JDBC URL
    password: root
    username: root
  config:
    activate:
      on-profile: test
